app:
  container_name : numpapp
  build: .
  command: python -u app.py
  ports:
    - "5002:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  container_name : numpdb
  image: mongo:latest
  hostname: test_mongodb
  environment:
    - MONGO_INITDB_DATABASE=animal_db
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  volumes:
    - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  ports:
    - 27017:27017